name = "ARFFFiles"
uuid = "da404889-ca92-49ff-9e8b-0aa6b4d38dc8"
authors = ["Christopher Doris <github.com/cjdoris>"]
version = "1.5.1"

[workspace]
projects = ["test"]

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CategoricalArrays = "0.10, 1.0"
Dates = "1"
Parsers = "2.8"
Tables = "1.12"
julia = "1.6"
